### PR TITLE
automatically refresh commits and history views when bringing the app to the foreground

### PR DESCRIPTION
**Pull request by mikeash**

### CODE REVIEW

**Comment by Uncommon** [comment]
This fork hasn't been under active development for a while. The last commit to the master branch was almost two years ago.

**Comment by koraktor** [comment]
That said, other forks like [laullon's](https://github.com/laullon/gitx) already have that feature.

**Comment by mikeash** [comment]
Is there a good fork to work against that people are contributing to that doesn't have the extra UI addons that most of them seem to be moving towards?

**Comment by Uncommon** [comment]
laullon/gitx is currently the most active fork. He and I are also working on a rewrite at Uncommon/Xit.

**Pull request closed without merging**
